# Generated by Django 2.2.3 on 2019-12-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
