# Generated by Django 2.2.3 on 2019-12-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='P_content',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
