# Generated by Django 2.2.3 on 2019-12-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_p_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='P_content',
            field=models.CharField(default=4, max_length=1000),
            preserve_default=False,
        ),
    ]
