# Generated by Django 2.2.3 on 2019-12-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191221_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='P_content',
        ),
    ]
