# Generated by Django 2.2.3 on 2019-12-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaking', models.CharField(max_length=50)),
                ('head_data', models.DateTimeField(auto_now_add=True)),
                ('head_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(default='1--', on_delete=django.db.models.deletion.CASCADE, to='news.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_upload',
            field=models.FileField(blank=True, help_text='(optional)', upload_to='article/videos'),
        ),
    ]
