# Generated by Django 2.2.3 on 2019-12-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191223_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
