# Generated by Django 2.2.3 on 2019-12-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_livest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
