# Generated by Django 2.2.3 on 2019-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='(optional)', upload_to='article/thumbnails'),
        ),
    ]
