# Generated by Django 2.2.3 on 2019-12-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20191224_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Category',
        ),
    ]
