# Generated by Django 3.0.1 on 2019-12-26 13:15

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20191224_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='descr',
            field=ckeditor.fields.RichTextField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
