# Generated by Django 3.0.1 on 2019-12-26 15:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20191226_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='descr',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
