# Generated by Django 3.0.1 on 2020-01-03 14:18

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20191226_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='livest',
            name='videos',
            field=models.URLField(default=8, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livest',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
